### ISSUE TITLE
remove json dependency for ruby > 1.8

### ISSUE THREAD

**Issue by logicminds** [ploubser/JSON-Grep#30]
Ruby comes with json now.  Do we still need the json dependency?  Can we replace with `s.add_runtime_dependency 'json' if RUBY_VERSION =~ /^1\.8/`.  This is preventing me from bundling this gem into a package since it requires compilation

**Comment by ripienaar** [comment]
+1 to that

**Comment by ploubser** [comment]
Works for me.

**Comment by ripienaar** [comment]
I'm thinking we should just remove the json dependency all together yeah? It's not like any reasonable person expects stuff to work on 1.8?

**Comment by ploubser** [comment]
Yeah, agree.

**Comment by ripienaar** [comment]
https://github.com/ploubser/JSON-Grep/pull/34

**Comment by ploubser** [comment]
PR has been merged. I will push a 1.5.0 later today unless there is anything else

**Comment by ripienaar** [comment]
@ploubser mind giving me a few days so I can see if anything else crops up? I might try getting some rubocop in here as well but omg :P

**Comment by ploubser** [comment]
Haha, good luck with that. No worries, just let me know when you're ready.
