### ISSUE TITLE
utility to validate an expression is valid

### ISSUE THREAD

**Issue by ripienaar** [ploubser/JSON-Grep#31]
I'd like a way to check a expression is valid, so something like

```ruby
def validate_expression(expression)
   Parser.new(expression)
   nil
rescue
   $!.message
end
```

This gives me a way to softly pre-check an expression a user gives, of course I can do `JGrep::Parser.new` myself but having something on `JGrep.validate_expression` seems to communicate the publicness of that method better - I assume Parser is `private`

**Comment by ripienaar** [comment]
Happy to do the PR just checking it's ok first

**Comment by ploubser** [comment]
👍

**Comment by ripienaar** [comment]
@ploubser will you have objections to a big code retab to more typical ruby spacing etc? I'd do that as a separate PR

**Comment by ploubser** [comment]
@ripienaar  that sounds great.

**Comment by ripienaar** [comment]
https://github.com/ploubser/JSON-Grep/pull/33

**Comment by ploubser** [comment]
PR's been merged. Closing.
