### ISSUE TITLE
unused methods

### ISSUE THREAD

**Issue by ripienaar** [ploubser/JSON-Grep#40]
while making it all pretty I noticed the 2 methods `JGrep.hash_to_array` and `JGrep.array_to_hash` they seem completely unused, they also seem a bit cringe worthy since all they do is print stuff to STDOUT and then return the string returned from `puts`.  They also `exit`.

Any idea whats up with these @ploubser something we can just yank?

**Comment by ploubser** [comment]
@ripienaar Kill it with fire.

**Comment by ripienaar** [comment]
https://github.com/ploubser/JSON-Grep/pull/41
